# Making a Change to this package?
# REMEMBER TO UPDATE the .yaml files for the following packages:
#   moose-dev/*
#
# As well as any directions pertaining to modifying those files.
{% set version = "2023.11.29" %}

package:
  name: moose-peacock
  version: {{ version }}

source:
  path: ../peacock

build:
  number: 0

requirements:
  host:
    # TODO: Try to remove when this version settles down among other conda-forge packages
    - openssl <3.2.0a # [osx]
  run:
    - {{ moose_mpich }}
    - pyaml
    - numpy
    - pandas
    - pyqt
    - matplotlib
    - vtk
    # TODO: Try to remove when this version settles down among other conda-forge packages
    - {{ pin_compatible('openssl', upper_bound='3.2') }} # [osx]
  # Python min/max constraints
  run_constrained:
    - python <{{3.11}}

test:
  imports:
    - PyQt5
    - pandas
    - matplotlib
    - vtk

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: >
    This superficial module (moose-peacock) acts as a top-level module designed to provide all
    dependencies required in order to run Peacock.

extra:
  recipe-maintainers:
    - milljm
