name: Documentation

on:
  # Triggers the workflow on push or pull request
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Newer commits should cancel old runs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: sudo apt install graphviz
      - run: pip install -r requirements.txt
      - run: |
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_UNITY_BUILD=OFF \
            -DNEML2_UNIT=ON \
            -DNEML2_REGRESSION=OFF \
            -DNEML2_VERIFICATION=OFF \
            -DNEML2_BENCHMARK=OFF \
            -DNEML2_PROFILING=OFF \
            -DNEML2_DOC=ON \
            .
      - run: make doc-syntax -j 2
      - run: make doc-html
      - run: cat doc/doxygen.log
      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: doc/build/html
          single-commit: true
